spring:
  application:
    name: demo-app  
    
server:
  port: 8080

security.enabled-csrf: false

security:
   basic:
    enabled: false

logging:
  level:
    root: INFO

management:
  security:
    enabled: false 
    
name : Pradeep
